apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  labels:
    app: wiki

spec:
  selector:
    matchLabels:
      app: 'wiki'

  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 'wiki'
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: wiki
          image: 'ghcr.io/requarks/wiki:2'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DB_PASS
              value: wikijs
            - name: DB_NAME
              value: wikijs
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: wikijs
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: db
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3000
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3000
          startupProbe:
            failureThreshold: 60
            successThreshold: 1
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db

spec:
  selector:
    matchLabels:
      app: 'db'

  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 'db'
    spec:
      containers:
        - imagePullPolicy: Always
          name: db
          image: postgres:11-alpine
          env:
            - name: POSTGRES_DB
              value: wikijs
            - name: POSTGRES_PASSWORD
              value: wikijs
            - name: POSTGRES_USER
              value: wikijs
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
  resourceVersion: "1657267"
  uid: c23a845d-1efd-4fb7-a07a-3ac3edc2b4e8
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dbport
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
  sessionAffinity: None
  type: ClusterIP